### ISSUE TITLE
commit "Marshmallow time!" cause crash on 5.1

### ISSUE THREAD

**Issue by iptux** [PaperAirplane-Dev-Team/BlackLight#1849]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{us.shandian.blacklight.snapshot/info.papdt.blacklight.ui.main.MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:422)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
	at info.papdt.blacklight.ui.common.ToolbarActivity.onCreate(ToolbarActivity.java:46)
	at info.papdt.blacklight.ui.main.MainActivity.onCreate(MainActivity.java:187)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more
```

* Google 过了，然并卵
* revert 掉后没有这个问题

:joy:

**Comment by PeterCxy** [comment]
well let me take a look (and who made the bullshit AppCompat-v7?)

**Comment by PeterCxy** [comment]
Will chaning theme to "XXX.NoActionBar" and remove the windowActionBar lines fix this issue?

**Comment by PeterCxy** [comment]
Ok I have found why. Will fix soon.

**Comment by AbuYoung** [comment]
@PeterCxy 前后不过三分钟…
